fraction_replacers = {
    "one tenth": "1/10",
    "and one tenth": "1/10",
    "one ninth": "1/9",
    "and one ninth": "1/9",
    "one eighth": "1/8",
    "and one eighth": "1/8",
    "one seventh": "1/7",
    "and one seventh": "1/7",
    "one sixth": "1/6",
    "and one sixth": "1/6",
    "one fifth": "1/5",
    "and one fifth": "1/5",
    "a quarter": "1/4",
    "and a quarter": "1/4",
    "one third": "1/3",
    "and a third": "1/3",
    "a half": "1/2",
    "and a half": "1/2",
    "two fifths": "2/5",
    "and two fifths": "2/5",
    "three fifths": "3/5",
    "and three fifths": "3/5",
    "two thirds": "2/3",
    "and two thirds": "2/3",
    "three quarters": "3/4",
    "and three quarters": "3/4",
    "four fifths": "4/5",
    "and four fifths": "4/5",
    "five sixths": "5/6",
    "and five sixths": "5/6",
}